### ISSUE TITLE
Pluggable Scheduler/Provider backends

### ISSUE THREAD

**Issue by nemosupremo** [nemosupremo/vault-gatekeeper#14]
While writing tests I came across the fact that we don't only have to check with mesos to see if an incoming request for a token is valid.

If possible we could add:
- A testing backend that fails/grants requests based on some test requirements
- k8s?
- nomad?
- swarm?

**Comment by aantono** [comment]
Would there be an interest in maybe cooperating on adding support for ECS or a plain Docker?
