### ISSUE TITLE
Support list of vault addresses in "-vault" CLI arg (VAULT_ADDR env var)

### ISSUE THREAD

**Issue by ghost** [nemosupremo/vault-gatekeeper#16]
Currently, the -vault CLI arg (VAULT_ADDR env var) only allows for one Vault address to be listed.
In an environment where there is a cluster with multiple Vault instances, it would be good for the setting to allow for the set of instances to be listed (similar to the MESOS_MASTER setting).

e.g., VAULT_ADDR=https://<vault-instance-1>:8200,<vault-instance-2>:8200,<vault-instance-3>:8200,<vault-instance-4>:8200,<vault-instance-5>:8200

**Comment by jamessoubry** [comment]
in cluster mode isnt only one active so you should only be pointing to, for example, with consul HA: http://active.vault.service.consul:8200

**Comment by philippescar** [comment]
In any case if you send a request to a `standby` node it will forward to the active master
