### ISSUE TITLE
VGM complaining about task running too long

### ISSUE THREAD

**Issue by sdwr98** [nemosupremo/vault-gatekeeper#19]
Hi all,

We're seeing an issue in one of our environments where we're seeing occasional failures of VGM to provide a token, with the error message: 

`2016/10/20 18:30:39 Failed to create token pair for 10.3.1.197:58262 (Task Id: ct:1476988200000:0:legacy_google_verify_addresses:). Reason: This task has been running too long to request a token.`

However, according to Mesos, that task had only been running for about a second (those timestamps are the start and stop time, respectively): 

`ct:1476988200000:0:legacy_google_verify_addresses: ChronosTask:legacy_google_verify_addresses  FAILED  2016-10-20T14:30:38-0400    2016-10-20T14:30:39-0400`

This is intermittent and happening to both nodes of a two-node VGM installation.  VGM and the Chronos tasks are all running in docker containers, and the Docker hosts as well as the Mesos masters are all running NTP and are in sync date-wise.  

Any ideas on how to go about further debugging?

**Comment by sdwr98** [comment]
Update:  The "task running too long" error message in the VGM error log is incorrect (maybe a cut-and-paste issue) but the real error is returned in the JSON body of the /token request.  We're seeing this: 

`Response from VGM: {"status":"Unsealed","ok":false,"error":"400: permission denied"}`

And in the Vault logs a second or two before, this: 

`2016/10/20 21:05:07 [INFO] expire: revoked 'auth/token/create/7e416e9759a9a353685eccf099b9b33375bcd4fe'`

Does that provide any more info?

**Comment by nemothekid** [comment]
My initial guess is the token you provided to vault doesn't have the right permissions in order to create tokens. Are you providing the same token to both instances? I'm not 100% sure, but it could be that a renewal on one machine is invalidating the token on another.

**Comment by sdwr98** [comment]
We've been running it in our environment with just one VGM instance (to rule out the very scenario that you mentioned).  Just a few minutes ago, I saw this error in the VGM log:

```
2016/10/25 19:57:39 Failed to lookup token. Not starting renewal watcher. Error: Get https://vault-sandbox.XXX.com/v1/auth/token/lookup-self: dial tcp: i/o timeout 
```

I haven't seen that every time, but I'm wondering if there's some sort of issue with our networking environment.  

Having said that, do you think it would be worth sealing the VGM instance in a case like this?  Since not restarting the renewal watcher will guarantee an unusable instance.

**Comment by nemothekid** [comment]
That would make sense. If I have this right

* We try to renew a token
* It fails due to a network error
* We miss the window for renewing the token
* We *should* seal the instance here as the token could not be renewed.

**Comment by sdwr98** [comment]
That would be great.
