### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by siddharthist** [nemosupremo/vault-gatekeeper#3]

**Comment by nemothekid** [comment]
Just to update on this -

I'm trying to get integration tests up and running on travis - setting up the integration environment with mesos is the current hurdle. When thats done I'll cut a release with both tests and #4.

**Comment by nemothekid** [comment]
Status:

Currently *most* interactions between Vault Gatekeeper and Vault itself are now tested. I'm still working on getting the Mesos side tested (trying to use minimesos to get it running), but its proving to be a bit difficult.
