### ISSUE TITLE
HTTP is enforced to communicate with Mesos

### ISSUE THREAD

**Issue by mlowicki** [nemosupremo/vault-gatekeeper#34]
https://github.com/ChannelMeter/vault-gatekeeper-mesos/blob/master/mesos.go#L121

"http://" is hardcoded and it should be possible to use HTTPS as well to avoid eavesdropping.

**Comment by mlowicki** [comment]
what is strange is that if I set `MESOS_MASTER` to ` `https://m1.mesos.services.ams.osa,m2.mesos.services.ams.osa,m3.mesos.services.ams.osa` I see errors like `x509: certificate signed by unknown authority`. Any clue what is happening here? I'm using latest Docker image.

**Comment by nemosupremo** [comment]
I'm thinking about a fix like this -

https://github.com/ChannelMeter/vault-gatekeeper-mesos/commit/e485d873917d8918f18cbdbd28e675e46d9dcc97

However, I don't think using a `zks` protocol is idiomatic, and it doesn't control whether or not the connect to *zookeeper* is encrypted. Nonetheless I'm actually traveling in a couple hours so I wont get back to this for a couple day.

**Comment by mlowicki** [comment]
LGTM. Thanks for fast reaction. Looking forward to try it out.

**Comment by mlowicki** [comment]
Would be good though to pass custom CA cert while talking with Mesos (In our case we're using HTTPS). In the same way as with `VAULT_CAPATH` or `VAULT_CACERT`.

**Comment by mlowicki** [comment]
@nemosupremo any news on this one?

**Comment by nemosupremo** [comment]
Hi sorry for the slowness on merging this - I ended up on going on a trip to very busy Europe shortly after I wrote this. I'll try to merge this and cut a new release before the end of the week

**Comment by mlowicki** [comment]
Hey @nemosupremo. Friendly reminder :-)

**Comment by mlowicki** [comment]
@nemosupremo ping
