### ISSUE TITLE
New Release tag?

### ISSUE THREAD

**Issue by vmahedia** [nemosupremo/vault-gatekeeper#52]
Numerous issues and enhancements have been made but the release has not happened for almost one and a half year.

**Comment by himadrisingh001** [comment]
Yes, it would be great to have a new release. AWS EC2 login methods are in master only right now.

**Comment by vmahedia** [comment]
@cookandy  that fix is in, as well as the nested policy as of today. It's just a matter of cutting a tag and making a release. @nemosupremo We can help you with that if you are crunched on time.

**Comment by FierceElements** [comment]
+1, we also need these features that are in master but not yet released

**Comment by vmahedia** [comment]
>things like -seal-http-status don't exist in the latest 0.5.3 release.

The fix for this is in the latest master if you want to pull it. It was not working before this fix.

**Comment by nemosupremo** [comment]
There has been a new release on master, with v1.0.0, which includes all the running features and a new architecture.
