### ISSUE TITLE
Question on building/installing gatekeeper-cli

### ISSUE THREAD

**Issue by Rahkeesh** [nemosupremo/vault-gatekeeper#70]
I've been following the documentation for how to get this setup ran into a roadblock doing something that seemed like it should be basic.

> We must then write our policy to the policy-path where Gatekeeper can expect to find it. The easiest way to do this is with the Gatekeeper Cli.
> 
> `$ VAULT_TOKEN=some_token gatekeeper policy update --vault-addr http://localhost:8200 ./my-policy.json`
> 

This is the first time Gatekeeper Cli is suggested as a tool in the documentation. I can find it's documentation however this documentation doesn't cover anything about how this tool is build/installed. I'm somewhat familiar with Go so I know that generally you can make a Go program run by doing `go get -d .` to grab the dependencies and then some variant on `go build` to make the executable but that doesn't appear to work here and even if it did I'm pretty sure that the command I'd need to run it in the end wouldn't start with VAULT_TOKEN=some_token (not even sure why this is in front given that  there is a flag for your vault token mentioned in the documentation).

If you're going to suggest we use this tool, could we please have some instructions on how to get/build it.

**Comment by nemosupremo** [comment]
The CLI tool is the same binary as the server. Apologies if that isn't clear - you can download the binary from the [Releases](https://github.com/nemosupremo/vault-gatekeeper/releases) page. 

I'll update the documentation to make this clear.

**Comment by Rahkeesh** [comment]
Thanks for the fast reply.
