### ISSUE TITLE
{"unsealed":true,"error":"The role requested does not exist."}

### ISSUE THREAD

**Issue by shashankimanage** [nemosupremo/vault-gatekeeper#74]
I am trying to solve this but not able to get any help.
i have the policy in place as per the documentation.
btw not able to proceed futher because of this.

curl -X POST -d"{\"task_id\":\"n.9bc5088a-9e0f-11e9-a6d9-024258bea194\"}" 'http://localhost:9201/token'
{"unsealed":true,"error":"The role requested does not exist."}

**Comment by ericxnelson** [comment]
I'm getting this too but can't remember if I had a workaround that fixed it or not a few months back when I tested things out, or perhaps it's environmental.... idk.

Hopefully someone bumps this and if I figure out in the meantime will do so.

**Comment by nemosupremo** [comment]
If you are getting `ErrNoSuchRole`, that means the [AppRole](https://www.vaultproject.io/docs/auth/approle.html) you are trying to use doesn't exist. Let's say in your vault config you have `{ roles: ["test"] }` - you should have created an approle of the same name:

```sh
vault write auth/approle/role/test \
    secret_id_ttl=10m \
    secret_id_num_uses=1 \
    policies=default \
    token_ttl=60m \
    period=60m
```

Gatekeeper leverages approles, so the ACLs you need should be tied the AppRole. You should take a look at the [Getting Started](http://nemosupremo.github.io/vault-gatekeeper/docs/doc.html#getting-started) guide if you are having trouble.

**Comment by ericxnelson** [comment]
Thanks for the response! I'll have some time later today to jump back on this and will post what I find.
