### ISSUE TITLE
Support wildcard inside task name or a more robust (regexp?) matching

### ISSUE THREAD

**Issue by jsynowiec** [nemosupremo/vault-gatekeeper#76]
Metronome job task names are prefixed with a datetime string, e.g. `20190826135622VHRSz.task-name`, so the current matching can effectively only support **all tasks** at once via `mesos:metronome:*`. This means that we can't assign a specific AppRole and policy to a specific job "type". Or I don't see how.

Solution: either support an wildcard matching inside a task name, like `mesos:metronome:*.task-name` or introduce a more robust regexp matchers.

**Comment by nemosupremo** [comment]
Fixed by #77, I'll close this when I cut a release

**Comment by jsynowiec** [comment]
@nemosupremo any ETA on the next release? Is it hours/days away or weeks? Asking whether @drbig and I should build and deploy our own fork in the meantime ;)

**Comment by nemosupremo** [comment]
Fixed in v1.1.0
